### ISSUE TITLE
Deselect OptGroup items when clicking the Optgroup title

### ISSUE THREAD

**Issue by JordanSayner** [krazedkrish/select-multiple#14]
Hello,

I'm looking to deselect all the items within an optgroup. Currently, when clicking on the optgroup title, all items are selected. I then want to deselect them all in case its clicked by mistake, and i can have up to 20-30 items within a optgroup. So its painful to scroll through and click all of them to deselect.

I have found the lines of code that i need tweaking, i just cant figure out how to tweak it.

Lines 125 - 130

```
      if (that.options.selectableOptgroup){
        $selectableOptgroup.find('.ms-optgroup-label').on('click', function(){
          var values = $optgroup.children(':not(:selected, :disabled)').map(function(){ return $(this).val() }).get();
          that.select(values);
        });
      }
```

**Comment by JordanSayner** [comment]
Hi,

Just to let you know. I figured this out. I replaced this bit of code 

```
              var values = $optgroup.children(':not(:selected, :disabled)').map(function () { return $(this).val() }).get();
              that.select(values);
```

with this 

```
              var values = $optgroup.children(':not(:selected, :disabled)').map(function () { return $(this).val() }).get();

              if (values.length) {
                  var values = $optgroup.children(':not(:selected, :disabled)').map(function () { return $(this).val() }).get();
                  that.select(values);
              }
              else {
                  var values = $optgroup.children(':selected').map(function () { return $(this).val() }).get();
                  that.deselect(values);
              }
```

Not sure if its the best way, but it works for me.

**Comment by krazedkrish** [comment]
@JordanSayner I am so sorry, I just saw your message today. I have been away celebrating Dashain.

I am glad that you found the solution.
