### ISSUE TITLE
How to intitialize with JSON data and how to get selected values

### ISSUE THREAD

**Issue by dennryuu** [krazedkrish/select-multiple#18]
Just as the title, could you tell me how can I initialize the control by Json data
and how to get selected values.

**Comment by krazedkrish** [comment]
@dennryuu you can use select-multiple just like any other <select> tag
If you want to initialize by json data, you have to first add data to <select> tag just like any other select tag using and then initialize it with .selectMultiple();

1. So, you can define empty select

```html
<select id='select-options' multiple='multiple'>
</select>
```

2. add json data your way
Reference: https://stackoverflow.com/questions/4969754/jquery-append-to-select-with-an-array

3. initialize it as select multiple

```js
$('#select-options').selectMultiple(); 
```

4. add more data if you want

```js
 $('#select-options').selectMultiple('addOption', { value: 42, text: 'test 42', index: 0 });
```

5. get selected values

```js
$('#select-options').val();
```

I hope this answers your questions.
For documentation about the aboves you can refer to http://krazedkrish.com/select-multiple/#demos

**Comment by dennryuu** [comment]
It works. Thank you very much
