### ISSUE TITLE
How can I do get all the selected values?

### ISSUE THREAD

**Issue by selimcal** [krazedkrish/select-multiple#3]
I want to pass the values of chosen fields to an array. How can i do this?

**Comment by selimcal** [comment]
var prm = $(".prm");
for (var i = 0; i < prm.length; i++) {
   if (prm[i].type == "select-multiple") {
        var pv = $('select[name=' + prm[i].name + ']').val() || [];
        var parametre = { 'name': prm[i].name, 'values': pv };
        parametreler.push(parametre);
    }
}

**Comment by krazedkrish** [comment]
cool!

this kind of requirement seems to be general. So, you can send pull request to me with the code and the demo, in site. It will be helpful to others as well.

:)
